name: midnightmunchies
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  gif: ^2.3.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  responsive_grid_list: ^1.4.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  flutter_gcaptcha_v3: ^2.1.1
  firebase_database: ^11.2.0
  flutter_switch: ^0.3.2
  geolocator: ^12.0.0
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  flutter_cache_manager: ^3.4.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  provider: ^6.1.2
  # carousel_slider: ^5.0.0
  carousel_slider: ^4.2.1
  timeline_tile: ^2.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.0
  cloud_firestore: ^5.6.5
  lottie: ^3.3.1
  intl: ^0.20.2
  razorpay_web: ^2.0.2
  razorpay_flutter: ^1.3.4
  font_awesome_flutter: ^10.8.0
  dropdown_button2: ^2.3.9
  google_sign_in_platform_interface: ^2.5.0
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner.png
    - assets/images/burger.png
    - assets/images/midnightmunchies_logo.png
    - assets/images/midnightmunchies_logo_dark.png
    - assets/images/google_icon.png
    - assets/images/loader.gif
    - assets/images/restaurent.png
    - assets/images/delivery.png
    - assets/images/location_icon.png
    - assets/images/search_icon.png
    - assets/images/get.png
    - assets/doodle.json
