// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8L_udv_Bsug-fDS83zK1JsSE-IrMOnc',
    appId: '1:44734305698:web:84eb534d9b5dc4ddc60efb',
    messagingSenderId: '44734305698',
    projectId: 'midnight-munchies-adc86',
    authDomain: 'midnight-munchies-adc86.firebaseapp.com',
    storageBucket: 'midnight-munchies-adc86.firebasestorage.app',
    measurementId: 'G-1BXQKYYH47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zlSf634D6toAGmzAFdQZ52DaRbgtpp8',
    appId: '1:44734305698:android:32b1d95930020548c60efb',
    messagingSenderId: '44734305698',
    projectId: 'midnight-munchies-adc86',
    storageBucket: 'midnight-munchies-adc86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL12VxenzHfHX8ikiw-qmJyhKE8aJ7SD8',
    appId: '1:44734305698:ios:1b7601dfe5c74507c60efb',
    messagingSenderId: '44734305698',
    projectId: 'midnight-munchies-adc86',
    storageBucket: 'midnight-munchies-adc86.firebasestorage.app',
    iosClientId: '44734305698-t97keljdojidvo3bajd1o0v3b3uirblt.apps.googleusercontent.com',
    iosBundleId: 'com.example.midnightmunchies',
  );
}
